# 로컬에서 구동하는 개발 환경에 대한 설정
spring:
  datasource:
    url: jdbc:h2:./unihub_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

custom:
  site:
    domain: "${custom.dev.domain}"
    backUrl: "${custom.dev.backUrl}"
    frontUrl: "${custom.dev.frontUrl}"