# 로컬에서 구동하는 개발 환경에 대한 설정
spring:
  datasource:
    url: jdbc:h2:./unihub_dev;MODE=MySQL # 개발환경에서는 인메모리 H2 데이터베이스를 사용
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false

  data:
    redis:
      host: localhost # 로컬 Redis 서버 호스트
      port: 6379

logging:
  level: # 개발환경에서는 모든 TRACE와 DEBUG 로그를 확인할 수 있도록 설정
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

custom:
  site: # localhost 주소가 설정 됨
    domain: "${custom.dev.domain}"
    backUrl: "${custom.dev.backUrl}"
    frontUrl: "${custom.dev.frontUrl}"
