server:
  port: 8080

spring:
  application:
    name: unihub

  profiles:
    include: secret
    default: dev

  output:
    ansi:
      enabled: always

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  web:
    resources:
      add-mappings: false
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false

custom:
  dev: # 로컬 개발 환경 주소
    domain: localhost
    backUrl: "http://${custom.dev.domain}:${server.port}"
    frontUrl: "http://${custom.dev.domain}:3000"

  stg: # 테스트 서버 주소
    domain: sulee.site
    backUrl: "https://api.${custom.stg.domain}"
    frontUrl: "https://www.${custom.stg.domain}"

  prod: # 운영 서버 주소
    domain: un1hub.site
    backUrl: "https://api.${custom.prod.domain}"
    frontUrl: "https://www.${custom.prod.domain}"